/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tetris_console_Console */

#ifndef _Included_tetris_console_Console
#define _Included_tetris_console_Console
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tetris_console_Console
 * Method:    getScreenWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_tetris_console_Console_getScreenWidth
  (JNIEnv *, jclass);

/*
 * Class:     tetris_console_Console
 * Method:    getScreenHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_tetris_console_Console_getScreenHeight
  (JNIEnv *, jclass);

/*
 * Class:     tetris_console_Console
 * Method:    readBytes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_tetris_console_Console_readBytes
  (JNIEnv *, jclass);

/*
 * Class:     tetris_console_Console
 * Method:    drawChar
 * Signature: (IIC)V
 */
JNIEXPORT void JNICALL Java_tetris_console_Console_drawChar
  (JNIEnv *, jclass, jint, jint, jchar);

/*
 * Class:     tetris_console_Console
 * Method:    drawBorder
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_tetris_console_Console_drawBorder
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     tetris_console_Console
 * Method:    printString
 * Signature: (IIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tetris_console_Console_printString
  (JNIEnv *, jclass, jint, jint, jint, jstring);

/*
 * Class:     tetris_console_Console
 * Method:    clearLine
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_tetris_console_Console_clearLine
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     tetris_console_Console
 * Method:    clearBox
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_tetris_console_Console_clearBox
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     tetris_console_Console
 * Method:    clearScreen
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tetris_console_Console_clearScreen
  (JNIEnv *, jclass);

/*
 * Class:     tetris_console_Console
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tetris_console_Console_init
  (JNIEnv *, jclass);

/*
 * Class:     tetris_console_Console
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tetris_console_Console_shutdown
  (JNIEnv *, jclass);

/*
 * Class:     tetris_console_Console
 * Method:    refresh
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tetris_console_Console_refresh
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
